version: "3.8"

services:
  sqlserver:
    build:
      context: ./scripts
      dockerfile: sqlserver.Dockerfile
    env_file:
      - ./adventureworksapi/Presentation/.env  # Ruta al archivo .env
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts
      - ./backups:/scripts/backups
    command: /bin/bash /scripts/init-db.sh

  adventureworksapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./adventureworksapi/Presentation/.env  # Ruta al archivo .env
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
