version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Elasticp!"
      ACCEPT_EULA: "Y"
    ports:
      - "1469:1433"
    volumes:
      - ./scripts:/scripts
      - ./backups:/scripts/backups
    user: root  # Ejecutar como root para permisos de instalación
    command: /bin/bash /scripts/init-db.sh

  adventureworksapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    depends_on:
      - sqlserver
